
const nationalities = [
    "Afghan",
    "Albanian",
    "Algerian",
    "American",
    "Andorran",
    "Angolan",
    "Antiguan",
    "Argentine",
    "Armenian",
    "Australian",
    "Austrian",
    "Azerbaijani",
    "Bahamian",
    "Bahraini",
    "Bangladeshi",
    "Barbadian",
    "Belarusian",
    "Belgian",
    "Belizean",
    "Beninese",
    "Bhutanese",
    "Bolivian",
    "Bosnian",
    "Botswanan",
    "Brazilian",
    "Bruneian",
    "Bulgarian",
    "Burkinabe",
    "Burmese",
    "Burundian",
    "Cambodian",
    "Cameroonian",
    "Canadian",
    "Cape Verdean",
    "Central African",
    "Chadian",
    "Chilean",
    "Chinese",
    "Colombian",
    "Comoran",
    "Congolese",
    "Costa Rican",
    "Croatian",
    "Cuban",
    "Cypriot",
    "Czech",
    "Danish",
    "Djiboutian",
    "Dominican",
    "Dutch",
    "East Timorese",
    "Ecuadorean",
    "Egyptian",
    "Emirati",
    "Equatorial Guinean",
    "Eritrean",
    "Estonian",
    "Ethiopian",
    "Fijian",
    "Filipino",
    "Finnish",
    "French",
    "Gabonese",
    "Gambian",
    "Georgian",
    "German",
    "Ghanaian",
    "Greek",
    "Grenadian",
    "Guatemalan",
    "Guinea-Bissauan",
    "Guinean",
    "Guyanese",
    "Haitian",
    "Honduran",
    "Hungarian",
    "Icelander",
    "Indian",
    "Indonesian",
    "Iranian",
    "Iraqi",
    "Irish",
    "Israeli",
    "Italian",
    "Ivorian",
    "Jamaican",
    "Japanese",
    "Jordanian",
    "Kazakh",
    "Kenyan",
    "Kittitian",
    "Kuwaiti",
    "Kyrgyz",
    "Laotian",
    "Latvian",
    "Lebanese",
    "Liberian",
    "Libyan",
    "Liechtenstein",
    "Lithuanian",
    "Luxembourgish",
    "Macedonian",
    "Malagasy",
    "Malawian",
    "Malaysian",
    "Maldivian",
    "Malian",
    "Maltese",
    "Marshallese",
    "Mauritanian",
    "Mauritian",
    "Mexican",
    "Micronesian",
    "Moldovan",
    "Monacan",
    "Mongolian",
    "Montenegrin",
    "Moroccan",
    "Mozambican",
    "Namibian",
    "Nauruan",
    "Nepalese",
    "New Zealander",
    "Nicaraguan",
    "Nigerian",
    "Nigerien",
    "North Korean",
    "Norwegian",
    "Omani",
    "Pakistani",
    "Palauan",
    "Palestinian",
    "Panamanian",
    "Papua New Guinean",
    "Paraguayan",
    "Peruvian",
    "Polish",
    "Portuguese",
    "Qatari",
    "Romanian",
    "Russian",
    "Rwandan",
    "Saint Lucian",
    "Salvadoran",
    "Samoan",
    "San Marinese",
    "Sao Tomean",
    "Saudi",
    "Senegalese",
    "Serbian",
    "Seychellois",
    "Sierra Leonean",
    "Singaporean",
    "Slovak",
    "Slovenian",
    "Solomon Islander",
    "Somali",
    "South African",
    "South Korean",
    "South Sudanese",
    "Spanish",
    "Sri Lankan",
    "Sudanese",
    "Surinamese",
    "Swazi",
    "Swedish",
    "Swiss",
    "Syrian",
    "Taiwanese",
    "Tajik",
    "Tanzanian",
    "Thai",
    "Togolese",
    "Tongan",
    "Trinidadian",
    "Tunisian",
    "Turkish",
    "Turkmen",
    "Tuvaluan",
    "Ugandan",
    "Ukrainian",
    "Uruguayan",
    "Uzbek",
    "Vanuatuan",
    "Venezuelan",
    "Vietnamese",
    "Yemeni",
    "Zambian",
    "Zimbabwean"
]
const genders = ['male', 'female', 'non binary']

const civil_statuses = [
    "Single",
    "Married",
    "Divorced",
    "Widowed",
    "Separated",
    "Engaged",
    "In a Civil Partnership",
    "In a Domestic Partnership",
    "Annulled",
    "Common-Law"
]

const position_levels = [
    "Intern",
    "Entry Level",
    "Associate",
    "Mid Level",
    "Senior",
    "Lead",
    "Manager",
    "Director",
    "Vice President",
    "C-Level",
    "Owner"
];

const specializations = [
    "Software Development",
    "Data Science",
    "Cybersecurity",
    "Network Administration",
    "Database Administration",
    "Cloud Computing",
    "Project Management",
    "Business Analysis",
    "UX/UI Design",
    "Digital Marketing",
    "Financial Analysis",
    "Human Resources",
    "Sales",
    "Customer Service",
    "Healthcare Management",
    "Education and Training",
    "Legal Services",
    "Engineering",
    "Research and Development",
    "Content Creation",
    "Graphic Design",
    "Product Management",
    "Quality Assurance",
    "Supply Chain Management",
    "Operations Management",
    "Technical Support",
    "IT Consulting",
    "Mobile App Development",
    "Game Development",
    "Artificial Intelligence",
    "Machine Learning",
    "Public Relations",
    "Advertising",
    "Real Estate",
    "Event Planning",
    "Hospitality Management",
    "Tourism Management",
    "Environmental Science",
    "Social Work",
    "Psychology",
    "Journalism",
    "Media Production",
    "Architecture",
    "Urban Planning",
    "Construction Management",
    "Logistics",
    "Biotechnology",
    "Pharmaceuticals"
];

const industries = [
    "Information Technology",
    "Finance",
    "Healthcare",
    "Education",
    "Manufacturing",
    "Retail",
    "Hospitality",
    "Construction",
    "Transportation",
    "Real Estate",
    "Energy",
    "Telecommunications",
    "Media",
    "Entertainment",
    "Legal",
    "Non-Profit",
    "Government",
    "Aerospace",
    "Agriculture",
    "Automotive",
    "Biotechnology",
    "Chemical",
    "Consumer Goods",
    "Defense",
    "E-commerce",
    "Insurance",
    "Marketing",
    "Pharmaceuticals",
    "Public Relations",
    "Research",
    "Tourism",
    "Utilities",
    "Food and Beverage",
    "Textiles",
    "Mining",
    "Logistics",
    "Marine",
    "Consulting",
    "Architecture",
    "Design",
    "Environmental Services",
    "Human Resources",
    "Engineering",
    "Event Planning",
    "Sports",
    "Fitness",
    "Fashion",
    "Arts and Culture",
    "Social Services",
    "Renewable Energy"
];



export default {
    nationalities,
    genders,
    civil_statuses,
    position_levels,
    specializations,
    industries
}